language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - composer self-update
  - composer global require hirak/prestissimo 0.3.4

install:
  - composer install -o --dev --prefer-dist

script: ./vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer
    - $HOME/.cache/composer
    - $HOME/.config/composer
